#!/usr/bin/osascript
--
-- SYNOPSIS
--
--		prepare-simulator [ device ]
--
-- DESCRIPTION
--
-- Prepares the iPhone Simulator for use on the command line.
--
-- The device parameter specifies what device type to simulate.
-- This may be any value listed in the simulator's Hardware > Device
-- menu.  The default value is iPhone.
--
on run argv
	try
		set device_type to item 1 of argv
	on error
		set device_type to "iPhone"
	end try
	activate application "iPhone Simulator"
	tell application "System Events" to tell menu bar of process "iOS Simulator"
		click menu item device_type of menu "Device" of menu item "Device" of menu "Hardware"
		click menu "iOS Simulator"'s menu item "Quit iOS Simulator"
	end tell
end run
